### ISSUE TITLE
Add Show Next/Previous Repl History Entry commands

### ISSUE THREAD

**Issue by mtsbarbosa** [afucher/clojure-repl-intellij#66]
**Describe the bug**
When on repl terminal run inside the IntelliJ with the plugin, once arrow up or down are pressed nothing happens, instead of navigating through history of evals done on that repl 

**To Reproduce**
1. Run repl
2. Type `(+ 1 1)` and enter
3. Press arrow up

**Expected behavior**
`(+ 1 1)` should appear again, once a new eval is done both should appear in a sequence.

**Screenshots**

**Environment (please complete the following information):**
 - IntelliJ Version: IDEA 2023.1.6 (Community Edition)
 - OS: MacOS

**Additional context**
-

**Comment by afucher** [comment]
Hey @mtsbarbosa, thanks for reporting.
This plugin is more based on Cider and Calva, than Cursive. Why this matter? Because they have a different approach, we focus on have most of the forms to eval inside your own code, so if you need to evaluate it again is easier, like using Rich Comments. So, we encourage you to try this approach more than use directly the REPL.

After pointing that, this is a good enhancement to add to the plugin, using `Opt/Ctrl + Up` `Opt/Ctrl + Down`
